version: '2.1'

services:
  bookinfo--react-node-mongo-graphql---docker-:
    image: bookinfo--react-node-mongo-graphql---docker-
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js